title: Schema.org
description: Schema.org provides schemas for structured data on the Internet
baseurl: "/gh_pages"
url: "https://schemaorg.github.io"
repository: "schemaorg/gh_pages"

# GitHub Pages settings
theme: null
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

# Process all files
markdown: kramdown
include:
  - "*.html"
  - "*.md"
  - "_*"
  - "*.css"
  - "*.js"

# Force processing of HTML files
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Ensure front matter is processed
frontmatter:
  enabled: true

# Collections for schema types
collections:
  types:
    output: true
    permalink: /:name
  properties:
    output: true
    permalink: /:name

# Default layout
defaults:
  - scope:
      path: ""
      type: "types"
    values:
      layout: "type"
  - scope:
      path: ""
      type: "properties"
    values:
      layout: "property"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor